### ISSUE TITLE
Confused about conflicting parselets for the same token

### ISSUE THREAD

**Issue by chasewalden** [munificent/bantam#2]
Forgive me, but I was reading your tutorial and then looking at the code and noticed this.

https://github.com/munificent/bantam/blob/05276a6f24657630b86a3edeae0a81233512c16d/src/com/stuffwithstuff/bantam/BantamParser.java#L19-L20

The parselets are registered into a HashMap, which means that CallParselet will overwrite the GroupParselet, right? 

Is this intended?

**Comment by berar** [comment]
Yes, you are right. The key value of TokenType.LEFT_PAREN will point
to CallParselet
since it was put after GroupParselet into the map.

But which tutorial have you been reading? I think this code base has very
little to do with me.

**Comment by chasewalden** [comment]
http://journal.stuffwithstuff.com/2011/03/19/pratt-parsers-expression-parsing-made-easy/

Sorry. Tutorial was probably the wrong word. It was a blog post that I was reading to understand Pratt Parsers better.

**Comment by berar** [comment]
It's fine.

I just don't understand how you found my email and asked me lol

**Comment by chasewalden** [comment]
I am not sure either.

I simply posted an issue on the github project hosting the code. How you we’re notified is beyond me.

**Comment by munificent** [comment]
This was probably not the best use of Java overloading on my part. There are two register methods, one that takes an `InfixParselet` as the second parameter and one that takes a `PrefixParselet`. `GroupParselet` is a `PrefixParselet` and `CallParselet` is an `InfixParselet`, so they get registered separately.

**Comment by chasewalden** [comment]
Ahh, I see. I spaced on looking at the inheritance. That makes complete sense.
